repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.5
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  -   repo: https://github.com/python-poetry/poetry
      rev: '1.8.3'
      hooks:
      -   id: poetry-export
          args: ["-f", "requirements.txt", "-o", "./requirements.txt", "--without-hashes"]